# Generated by Django 4.2.10 on 2024-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=40, unique=True)),
                ('api_key', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente de identidade',
                'verbose_name_plural': 'Clientes de identidade',
            },
        ),
    ]
